### PR TITLE
fix: show not found page in case landing page is not found

### PR DESCRIPTION
**Pull request by vlnevyhosteny**

### CODE REVIEW

**Comment by vlnevyhosteny** [comment]
@ViolanteCodes You are trying that agains Heroku instance? Locally is just fine for me. 

Regarding to `landing-page/alternate-landing-page` It's not found for React (https://react-starter-buttercms-demo.vercel.app/landing-page/alternate-landing-page) nor Django (https://django-starter-buttercms-demo.herokuapp.com/landing-page/alternate-landing-page).

**Comment by ViolanteCodes** [comment]
@vlnevyhosteny it doesn't work either locally or on a freshly deployed heroku instance for me: [video](https://share.getcloudapp.com/nOuXX64k)

Yes, we have tickets in to fix both the django landing page and react landing page issues on our end. If this seems like its not going to be easily fixable, let me know, and I can let the team know where we're at with this feature and if we want to pursue it further as it's not as crucial as the other elements.

**Comment by vlnevyhosteny** [comment]
@ViolanteCodes 

> it doesn't work either locally or on a freshly deployed heroku instance for me: [video](https://share.getcloudapp.com/nOuXX64k)

I can see that you are on `feat/update-readme` branch which does not contain the fix. Pls switch to `fix/not-found-landing-page`.

Problem with `landing-page/alternate-landing-page` fixed in 97c2f99. It was not expecting missing sections.

**Comment by ViolanteCodes** [comment]
> @ViolanteCodes
> 
> > it doesn't work either locally or on a freshly deployed heroku instance for me: [video](https://share.getcloudapp.com/nOuXX64k)
> 
> I can see that you are on `feat/update-readme` branch which does not contain the fix. Pls switch to `fix/not-found-landing-page`.
> 
> Problem with `landing-page/alternate-landing-page` fixed in [97c2f99](https://github.com/ButterCMS/dotnet-starter-buttercms/commit/97c2f99f3f5d243c37d1ff53801be02902a1172f). It was not expecting missing sections.

@vlnevyhosteny 🤦 Yep, would help to be on right branch.

However, I just checked this out to what I believe is the correct branch/PR, and now the components are all missing completely?

[video](https://share.getcloudapp.com/5zurrbmO)

**Pull request merged**
